### ISSUE TITLE
False Positive: APT_NK_Methodology_Artificial_UserAgent_IE_Win7

### ISSUE THREAD

**Issue by afcyrus** [Neo23x0/signature-base#116]
The TASER International Evidence Sync utility, sync.exe, triggers this rule.

TASER International Evidence Sync utility: https://www.virustotal.com/gui/file/c369d107aa6987c92b01ff1855bf0661ea619fbe86906c53253a53c7ff60b389/community

**Comment by Neo23x0** [comment]
Thanks
