### ISSUE TITLE
No update

### ISSUE THREAD

**Issue by EstherMoellman** [Neo23x0/signature-base#124]
Hi,

Firstly, thank you for THOR LITE.

I subscribed to the newsletter, received the lic. file, and placed lic. file into my THOR extracted program folder.
However, (after many times) trying to update (thor-lite-util.exe update) to at least signature version “21.3.6-090007”, this message appears: "Mar  8 13:15:58 abc THOR_LITE_UTIL: Error: No valid license found".

After running THOR LITE, the THOR html file informs that signature version is “2021/02/15-094339".

Thank you!

**Comment by Neo23x0** [comment]
You should run thor-lite-util.exe from the program folder and not from a different location. 
Please use a cmd.exe to do that.

**Comment by EstherMoellman** [comment]
Firstly, thank you @Neo23x0 for your replay.

I always run thor-lite-util.exe from the program folder, and I always used cmd.exe.
Unfortunately, it's not working for me.

I removed THOR LITE, so I'm closing this issue.
Thank you anyway!
