### ISSUE TITLE
FP in apt_apt10.yar

### ISSUE THREAD

**Issue by bartblaze** [Neo23x0/signature-base#13]
Can you please remove the following line from the APT10 Yara rules file? 
`hash255 = "DA5EE020BEF41DC95C3532CBAA1EA8F4" 
`

This is a legit, signed binary by Microsoft (VT [results](https://virustotal.com/en/file/2e933b9823f15038eaf786f0898df03508a17ace8620a404edf5229aea0b9f18/analysis/)).

Thank you.

**Comment by Neo23x0** [comment]
Done - I've also mentioned this in the OTX pulse by @alienvault in which it also appears  https://otx.alienvault.com/pulse/58ebadf17c71a907e4d4b067/
