### ISSUE TITLE
False Positives for Asus LightningService.exe and AsPowerBar.exe

### ISSUE THREAD

**Issue by russdan** [Neo23x0/signature-base#135]
Both show as "Yara Rule MATCH: webshell_asp_runtime_compile".

```
20210318T08:35:12Z DESKTOP-xxxxx LOKI: Alert: MODULE: ProcessScan MESSAGE: Yara Rule MATCH: webshell_asp_runtime_compile PID: 13040 NAME: AsPowerBar.exe OWNER: xx CMD: "C:\Program Files (x86)\ASUS\AI Suite III\AsPowerBar\AsPowerBar.exe" PATH: C:\Program Files (x86)\ASUS\AI Suite III\AsPowerBar\AsPowerBar.exe
20210318T08:36:22Z DESKTOP-xxxxx LOKI: Alert: MODULE: ProcessScan MESSAGE: Yara Rule MATCH: webshell_asp_runtime_compile PID: 26276 NAME: LightingService.exe OWNER: SYSTEM CMD: "C:\Program Files (x86)\LightingService\LightingService.exe" PATH: C:\Program Files (x86)\LightingService\LightingService.exe
```

VirusTotal Scans
https://www.virustotal.com/gui/file/bad054b94d654d704eabd81177742edcc0ad33531178f80f0324e8932c513391/detection
https://www.virustotal.com/gui/file/a979343a5f778ac03c66552ba5ecaf3aedf6cb748f02699460148f5eeb9eff63/detection

**Comment by Neo23x0** [comment]
@2d4d Has this already been addressed?

**Comment by 2d4d** [comment]
@russdan can't reproduce it with the recent version, could you pls try with https://github.com/2d4d/signature-base/blob/master/yara/gen_webshells.yar ?
