### ISSUE TITLE
 SUSP_Reversed_Base64_Encoded_EXE

### ISSUE THREAD

**Issue by y0d4a** [Neo23x0/signature-base#148]
Hi, i got this alert on security onion for some .doc file, is this false positive?
because as i understand this rule, he only look for base64 strings inside executable files?

there IS some base64 parts in file, but seems it is just coincidence ?
`# grep -Eoc '[A-Za-z0-9+/]{4}*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)' DOCUMENT.doc`
`3707`

**Comment by Neo23x0** [comment]
It looks for reversed base64 encoded sections of PE files. Reversed means that the characters are reversed order, which is way of obfuscation. 
Why don't you just grep for the strings that appear in the rule or use `yara -r rule.yar -s DOCUMENT.doc` to see which string matched?
