### ISSUE TITLE
thor lite folder and url shortcut

### ISSUE THREAD

**Issue by JayDee168** [Neo23x0/signature-base#150]
20210607T13:40:07Z MAIL01 LOKI: Alert: MODULE: FileScan MESSAGE: FILE: C:\SCRIPTS\ExchangeChecks\thor10lite-win-pack\

20210607T13:40:05Z MAIL01 LOKI: Alert: MODULE: FileScan MESSAGE: FILE: C:\SCRIPTS\ExchangeChecks\thor10lite-win-pack\

20210607T13:42:04Z MAIL01 LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Downloads\SysinternalsSuite\Cacheset.exe

20210607T13:42:08Z MAIL01 LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Favorites\Links\Exchange Admin Center.url

20210607T13:42:08Z MAIL01 LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Favorites\Links\Exchange Outlook Web Access.url

20210607T13:42:08Z MAIL01 LOKI: Alert: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Favorites\Links\Microsoft Remote Connectivity Analyzer (2).url

20210607T13:42:08Z MAIL01 LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Favorites\Links\Set-ContentFilterConfig.url

20210607T13:42:08Z MAIL01 LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\Users\administrator\Favorites\Links\Verfahren zur Inhaltsfilterung.url

**Comment by Neo23x0** [comment]
There is information missing
