### ISSUE TITLE
ProxyShell webshell YARA rules - compiling error

### ISSUE THREAD

**Issue by santhuj93** [Neo23x0/signature-base#156]
When compiling YARA with python rules for ProxyShell webshell getting syntax error. Please find the below error and kindly suggest.

Error:

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Neo23x0** [comment]
I can't find any problems with these rules.
