### ISSUE TITLE
FP: CN_Honker__mysql_injectV1_1_Creak_DomainBlastingTool_super_Injection1

### ISSUE THREAD

**Issue by mime-frame** [Neo23x0/signature-base#16]
Rule: `CN_Honker__mysql_injectV1_1_Creak_DomainBlastingTool_super_Injection1`

Matched: `$s1, $s2, $s3` on this false positive:
- 53CCEBEFE6603534BB936653542EB62F
- c:\program files (x86)\oak telecom\comms suite\report\datasetclient.exe

Thanks @Neo23x0 - Your rules are awesome, thanks again for your open source contributions :)

**Comment by Neo23x0** [comment]
Done, thanks
