### ISSUE TITLE
Tetris YARA Rule - Includes simple rule

### ISSUE THREAD

**Issue by SasquatchSecurity** [Neo23x0/signature-base#172]
apt_tetris.yar includes a number of rules:

apt_CN_Tetris_JS_advanced_1
apt_CN_Tetris_JS_simple
apt_CN_Tetrisplugins_JS

The original author's blog and Github now reference an updated YARA rule without the "simple" rule in it. 

https://imp0rtp3.wordpress.com/2021/08/12/tetris/#rules
https://github.com/imp0rtp3/yara-rules/blob/main/2021-08-12%20Tetris/tetris_advanced.yar

I believe the "simple" rule is sometimes reporting false positives.

**Comment by Neo23x0** [comment]
I don't know if I want these rule in the rule set. They look as if someone didn't take the time to select the relevant strings and just left all of them in the set.
