### ISSUE TITLE
FP for WildNeutron_Sample_8

### ISSUE THREAD

**Issue by threatcrowd** [Neo23x0/signature-base#18]
Looks like it fires on the strings in https://github.com/subTee/nativecmd

Eg; c9a3b976ec9dfbc539ae87d8235c3589

**Comment by Neo23x0** [comment]
Hi, that's interesting. 
It seems to me that Wild Neutron has used @subTee's sources for their tools. To be honest, I have to check what it does and will then decide if I keep the rule in an improved form with a different name. 
What do you think? 
As someone who scans a system for suspicious objects, would you like to be informed about an object that is subTee's nativecmd? (especially when you know that a sample from the Wild Neutron sample set was a modified form of it)
```
$ yara -r ../signature-base/yara/apt_wildneutron.yar ./nativecmd/compiled -s
WildNeutron_Sample_8 /nativecmd/compiled/cmd.exe
0x1fff8:$x1: RunFile: couldn't load SHELL32.DLL!
0x20030:$x2: RunFile: couldn't find ShellExecuteExA/W in SHELL32.DLL!
0x22288:$x3: E\x00r\x00r\x00o\x00r\x00 \x00e\x00x\x00e\x00c\x00u\x00t\x00i\x00n\x00g\x00 \x00C\x00r\x00e\x00a\x00t\x00e\x00P\x00r\x00o\x00c\x00e\x00s\x00s\x00(\x00)\x00!\x00!\x00
0x20224:$x4: c\x00m\x00d\x00c\x00m\x00d\x00l\x00i\x00n\x00e\x00
0x20b06:$x5: Invalid input handle!!!
0x1f980:$s6: .\x00c\x00o\x00m\x00;\x00.\x00e\x00x\x00e\x00;\x00.\x00b\x00a\x00t\x00;\x00.\x00c\x00m\x00d\x00
0x2023a:$s8: c\x00m\x00d\x00e\x00x\x00t\x00v\x00e\x00r\x00s\x00i\x00o\x00n\x00
0x21b08:$s8: c\x00m\x00d\x00e\x00x\x00t\x00v\x00e\x00r\x00s\x00i\x00o\x00n\x00
0x2224c:$s10: "\x00%\x00s\x00"\x00 \x00/\x00K\x00 \x00%\x00s\x00
0x21040:$s12: DEBUG: Cannot allocate memory for ptrNextNode->ptrNext!
0x21318:$s13: F\x00a\x00i\x00l\x00e\x00d\x00 \x00t\x00o\x00 \x00b\x00u\x00i\x00l\x00d\x00 \x00f\x00u\x00l\x00l\x00 \x00d\x00i\x00r\x00e\x00c\x00t\x00o\x00r\x00y\x00 \x00p\x00a\x00t\x00h\x00
0x21104:$s14: DEBUG: Cannot allocate memory for ptrFileArray!
0x21170:$s15: %\x00-\x008\x00s\x00 \x00%\x00-\x003\x00s\x00 \x00 \x00%\x00*\x00s\x00 \x00%\x00s\x00 \x00 \x00%\x00s\x00
0x21a2c:$s16:  \x00%\x00%\x00%\x00c\x00 \x00i\x00n\x00 \x00(\x00%\x00s\x00)\x00 \x00d\x00o\x00 \x00
```

**Comment by threatcrowd** [comment]
Looking at SubTee's other repos on github I see now that they are mostly pen-testing tools.
So I agree it would be worth keeping, perhaps under a name like pentest_tool_subtee.
The old google code archive describes nativecmd as "Windows Native Shell".

Wild Neutron are a fascinating group so I was excited when I saw there was a hit for them on VT :)

**Comment by threatcrowd** [comment]
Oh and thanks for making all these rules available
