### ISSUE TITLE
False Positives for some Norton 360 files

### ISSUE THREAD

**Issue by GerardVIE** [Neo23x0/signature-base#181]
Hello, thank you for providing your scanner "Loki" for free! In case I can contribute and give something back, I would like to report some false positives. In case you already have enough to do and dont need this kind of reports (bcs I am o novice), pls just say so. Otherwise I would continue to send reports if they look important. 

Regarding the following "warnings" I checked all reported *.DAT, *.DAT.data, *.dll and the first of the *.qbd  -files at Virustotal and got a negative result. Anyway I do not trust Symantec, but this may have nothing to do with this results :-)

20220513T01:52:43Z ******-PC LOKI: Alert: MODULE: FileScan MESSAGE: FILE: C:\Program Files\Norton Security\NortonData\22.20.5.39\Definitions\SDSDefs\20220512.007\VIRSCAN8.DAT SCORE: 120 TYPE: UNKNOWN SIZE: 1446196 FIRST_BYTES: 53594d4301000000050c7a000600200000000000 / <filter object at 0x009B9760> MD5: 99db0ed85f39cf081d5fae93cf2fbed4 SHA1: 191b5e349a190f40420a74f85cd31168e8054e02 SHA256: 186b73f4d3e8e22f772bf2abdade5847b320263ff963e29bed2d5656c5d409b6 CREATED: Thu May 12 19:57:52 2022 MODIFIED: Thu May 12 19:57:52 2022 ACCESSED: Fri May 13 03:52:43 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_Mozilla SUBSCORE: 65 DESCRIPTION: Detects suspicious XORed keyword - Mozilla/5.0 REF: Internal Research AUTHOR: Florian Roth MATCHES: Str1: b290859693939ed0cad1cfREASON_2: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: ab97968cdf8f8d90988d9e92df9c9e9191908bdf9d9adf8d8a91df9691dfbbb0acdf92909b9a

20220513T01:52:44Z******-PC LOKI: Alert: MODULE: FileScan MESSAGE: FILE: C:\Program Files\Norton Security\NortonData\22.20.5.39\Definitions\SDSDefs\20220512.007\hlinks\VIRSCAN8.DAT.data SCORE: 120 TYPE: UNKNOWN SIZE: 1446196 FIRST_BYTES: 53594d4301000000050c7a000600200000000000 / <filter object at 0x009B98E0> MD5: 99db0ed85f39cf081d5fae93cf2fbed4 SHA1: 191b5e349a190f40420a74f85cd31168e8054e02 SHA256: 186b73f4d3e8e22f772bf2abdade5847b320263ff963e29bed2d5656c5d409b6 CREATED: Thu May 12 19:57:52 2022 MODIFIED: Thu May 12 19:57:52 2022 ACCESSED: Fri May 13 03:52:44 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_Mozilla SUBSCORE: 65 DESCRIPTION: Detects suspicious XORed keyword - Mozilla/5.0 REF: Internal Research AUTHOR: Florian Roth MATCHES: Str1: b290859693939ed0cad1cfREASON_2: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: ab97968cdf8f8d90988d9e92df9c9e9191908bdf9d9adf8d8a91df9691dfbbb0acdf92909b9a

20220513T01:57:16Z ******-PC LOKI: Warning: MODULE: FileScan MESSAGE: FILE: C:\Program Files (x86)\NortonInstaller\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC\562C4DD5\22.22.4.11\images\InsImage.dll SCORE: 60 TYPE: EXE SIZE: 1082624 FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / <filter object at 0x009B9718> MD5: 3c74d1838684811c1eec2a3c76844e0c SHA1: 4e8037952f34666df1254b1c95ab18c1e49d379a SHA256: d9b7a8b1c655031dc08bc7832aee742b4420e20031d66a8200862d93b373bec5 CREATED: Fri May 13 02:19:50 2022 MODIFIED: Thu May  5 11:47:23 2022 ACCESSED: Fri May 13 03:57:16 2022 REASON_1: File Name IOC matched PATTERN: \\(images|img|js|fonts|css|swf|themes|log|error_docs)\\[^\\]{,20}\.(exe|dll)$ SUBSCORE: 60 DESC: Suspicious EXE DLL in Non-Executable directory

20220513T02:01:42Z******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{32D8A1F7-D15C-427C-A2A3-E7927629D1F5}\{2A5008EB-331F-4E3C-808A-A8AC51771940}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 615474 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b3d2b3d7b385b38ab3 / <filter object at 0x009B9760> MD5: 1b82f294801b9d7ed586db7c904426d6 SHA1: ec87445f6e583976e6ac528e59ac14dc391a7b96 SHA256: 868d82276dece0d7721905af59a3a5e6d2c8cdab3b1159a99563beaa7e54f97d CREATED: Tue Feb  8 04:47:15 2022 MODIFIED: Tue Feb  8 04:47:15 2022 ACCESSED: Fri May 13 04:01:42 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

20220513T02:01:43Z ******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{3650175A-2AEC-4A6B-BC32-27C4EA297BD9}\{C2D61E7E-D656-444E-8FC3-30EBE99DE48C}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 326681 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b3d5b386b381b387b3 / <filter object at 0x009B97A8> MD5: 57229992661e31cebd8db48da27d491d SHA1: d2347a7b64f7eeee26981ee544eb0b8007a1eb21 SHA256: 6c8cac93aa97b6055d1aa6df6842151318c88a70cb6ee26b6e1d7a3a022db04d CREATED: Sat Dec 11 00:42:20 2021 MODIFIED: Sat Dec 11 00:42:20 2021 ACCESSED: Fri May 13 04:01:43 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

20220513T02:01:59Z ******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{75ED8FD1-8206-4662-BD4D-6FC07EFC67CA}\{80675807-152A-4D65-843A-141F8A4ABAC7}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 74757 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b380b387b381b386b3 / <filter object at 0x009B97A8> MD5: ae66afbd4c7e7aeeb9d172bb57fd9731 SHA1: d3b18b99589b7a3b45f59f473408fee069ee4519 SHA256: 76dead99d31cf842ab28e82da141a1fdfb246f312ba171f218bec1dbb19604a0 CREATED: Sat Dec 11 00:42:20 2021 MODIFIED: Sat Dec 11 00:42:20 2021 ACCESSED: Fri May 13 04:01:59 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

20220513T02:02:22Z ******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{C9FCFD68-850C-4193-B71D-40C44C93E33B}\{C651B55B-CA3A-4F49-823D-CBD56362D7F4}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 615474 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b3d2b3d7b385b38ab3 / <filter object at 0x009B9B50> MD5: 1b82f294801b9d7ed586db7c904426d6 SHA1: ec87445f6e583976e6ac528e59ac14dc391a7b96 SHA256: 868d82276dece0d7721905af59a3a5e6d2c8cdab3b1159a99563beaa7e54f97d CREATED: Tue Feb  8 04:47:14 2022 MODIFIED: Tue Feb  8 04:47:14 2022 ACCESSED: Fri May 13 04:02:22 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

20220513T02:02:22Z ******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{C9FCFD68-850C-4193-B71D-40C44C93E33B}\{DB88E4D3-B2DB-4230-9088-F397DF503304}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 675997 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b38bb383b380b38bb3 / <filter object at 0x009B97C0> MD5: 2245b7b96e01ac8a93311f907867672f SHA1: 8a7ad8292516fe45f2eee8515f17e1178f31f940 SHA256: cd256a5dee99934333e67920da907ac2b88bb0ef533db6a51b14d94946aaa787 CREATED: Tue Feb  8 04:47:14 2022 MODIFIED: Tue Feb  8 04:47:14 2022 ACCESSED: Fri May 13 04:02:22 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

20220513T02:02:35Z ******-PC LOKI: Notice: MODULE: FileScan MESSAGE: FILE: C:\ProgramData\Norton\{0C55C096-0F1D-4F28-AAA2-85EF591126E7}\NGC_22.20.5.39\QBackup\{FDFC4E9F-31BA-45A4-B704-F0700BB0BF35}\{15023566-BC43-46D3-A66E-3F15CC214C13}.qbd SCORE: 55 TYPE: UNKNOWN SIZE: 3716381 FIRST_BYTES: b0b0b3b3b3b9b2bbe1b3b3b3d1b382b383b3d1b3 / <filter object at 0x009B97F0> MD5: 17d9edc8e6d1c1ff7b713fd64aaf05bb SHA1: ed9b40a0d4a3504398fdbd62705f24a2ddccbd86 SHA256: 9550f86dbcd2093ad1ce46dc7e03b826044d4fafb736fe175c181259f79f7a79 CREATED: Sun Feb 13 01:56:37 2022 MODIFIED: Sun Feb 13 01:56:37 2022 ACCESSED: Fri May 13 04:02:35 2022 REASON_1: Yara Rule MATCH: SUSP_XORed_MSDOS_Stub_Message SUBSCORE: 55 DESCRIPTION: Detects suspicious XORed MSDOS stub message REF: https://yara.readthedocs.io/en/latest/writingrules.html#xor-strings AUTHOR: Florian Roth MATCHES: Str1: $%?l<>#+>-!l/-""#8l.)l>9"l%"ll!#()

**Comment by Neo23x0** [comment]
Yes, thanks, please report these findings. 
I always expect these reports but get far too few of them.
