### ISSUE TITLE
Invalid regex escape sequence in filename-iocs

### ISSUE THREAD

**Issue by aelth** [Neo23x0/signature-base#19]
Hello Neo23x0,

I noticed that several entries in filename-iocs have wrong regex escape sequence.
The entries with invalid '\\'-escapes are listed below:
```
# Hidden Cobra https://www.us-cert.gov/ncas/alerts/TA17-164A
(?i)C:\WINDOWS\SYSTEM32\CATROOT2\EDBCHK.LOG;75
(?i)C:\WINDOWS\SYSTEM32\MIMEFILTER.XML;75
(?i)C:\AWORK\CATROOT2;80
(?i)C:\WINDOWS\SYSTEM32\CATROOT2\{12CD0A1D-4EA2-11D1-8608-00C04F-C295EF};65
(?i)C:\WINDOWS\SYSTEM32\CATROOT2\{A750E6C3-38EE-17D5-85E5-10D03D-A378DE};65
```
Another invalid entry I found is the following: `Windows\\inf\\mdmeric3.\PNF ;65` (notice the .\\)

Best regards,
aelth

**Comment by Neo23x0** [comment]
Ah yes, thanks, I'll fix that

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/signature-base/commit/3e7c48c5ee35d4902fc665a51216b3de64ab893d
