### ISSUE TITLE
FP for APT10_Malware_Sample_Gen

### ISSUE THREAD

**Issue by azfayel** [Neo23x0/signature-base#22]
Hello 

I have a false positive for a specific tool devleoped interbnally APT10 LOKI: Alert: Yara Rule MATCH: APT10_Malware_Sample_Gen PID: 1460 NAME: dispnomade.exe CMD: "C:\Program Files (x86)\www\dispnomade.exe" 
Can you check that ? The MD5 is : b3d08e9b37ad6092fbf27af219a92d0c

Regards

RCL

**Comment by Neo23x0** [comment]
Hi and thanks, 

that's a match on the process memory of the the executable, which may contain only a substring of the C2 domains listed in the signature. 
I'll remove some short domains to avoid this in the future. The FP will probably go away when you restart the system or service. 

- Florian
