### ISSUE TITLE
false positive domains in "US-CERT TA17-293A"

### ISSUE THREAD

**Issue by marcuskbr** [Neo23x0/signature-base#226]
Most or all domains in the section "# US-CERT TA17-293A https://www.us-cert.gov/ncas/alerts/TA17-293A" seem to me false positives.  4 domains points to actual functional websites with real content.
I could also not find the domain plantengineering.com in the article nor in the article that supersedes TA17-293A.

So, it seems that the following domains should be removed:
cfemedia.com
grand-central.net
oilandgaseng.com
plantengineering.com
cfemedia.gcnpublishing.com
controleng.com

I suggest to remove the whole section including the IP addresses since the article is from 2017 and those IP addresses are most likely not used any more for the mentioned malware.

**Comment by Neo23x0** [comment]
fix in : https://github.com/Neo23x0/signature-base/commit/9745e9a3be0890d9a78c02ad0c1d461b754185af
