### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by derpeste** [Neo23x0/signature-base#282]
Hey there, we recently found this here on scanning our Mobile Iron Appliance with Thor Lite:
![thor_found](https://github.com/Neo23x0/signature-base/assets/142815139/68339b2c-6eed-4d77-817b-4c0829142721)

But it obviously seems not to be infected?
![grafik](https://github.com/Neo23x0/signature-base/assets/142815139/2019e31c-03ce-40b0-9225-fe23ecca7f97)

Thanks in advance,
Stefan

**Comment by Neo23x0** [comment]
Thanks, fixed in https://github.com/Neo23x0/signature-base/commit/1d8f1ad14856d18f24e5b0a9aab4795c59a6e816
