### ISSUE TITLE
Invalid MD5 entry

### ISSUE THREAD

**Issue by SkewedZeppelin** [Neo23x0/signature-base#305]
This one is a character short of 32.
Even the [source](https://www.pwc.co.uk/cyber-security/pdf/cloud-hopper-indicators-of-compromise-v3.pdf) has it wrong.
I tried to find it on other places, but those too were the same.

https://github.com/Neo23x0/signature-base/blob/7ad514199af574704c3f8da1f3daa1791cd535a3/iocs/hash-iocs.txt#L7355

**Comment by Neo23x0** [comment]
Thanks, I removed it : https://github.com/Neo23x0/signature-base/commit/50ca5d3b3dafae44ffdc84bf98476bb7c84f83d5
