### ISSUE TITLE
 gen_anydesk_compromised_cert_feb23 is bullshit in case of older binary

### ISSUE THREAD

**Issue by lhpitn** [Neo23x0/signature-base#325]
you should refine your rule, signed after date of incident not warn for any anydesk that is older then the hack, i use on my systems good old 7.1.12 for exactly that reason that i dont trust any later versions after that security case, so please refine that binary so that it only happies to stuff signed with this cert after a certain date to be determend but mid april 2021 is good

**Comment by lhpitn** [comment]
see also https://www.virustotal.com/gui/file/734f3577aa453fe8e89d6f351a382474a5dab97204aff1e194eee4e9fdff0a4a/community

**Comment by Neo23x0** [comment]
> so please refine that binary

No.

**Comment by lhpitn** [comment]
thajks for looking into it anyway

**Comment by lhpitn** [comment]
youre right, i remebered you can fake sign time by changing cmos time and switching off ntp

**Comment by lhpitn** [comment]
maybe whitelist certain sha sum pe files?

**Comment by lhpitn** [comment]
> so please refine that binary

sorry i guess i mean "please redefine the binary match rule " or sth like that, its to hot here, my brain feels like it's liquifying...
