### ISSUE TITLE
 signature-base/iocs/otx-c2-iocs.txt

### ISSUE THREAD

**Issue by zoni171** [Neo23x0/signature-base#4]
Hey Neo23x0,

Could you please fix these entries? Looks like they tied together. 

Thanks

domainsaccount.google.com.gmgoogle.comie.update-windows-microsoft.commail.upgoogle.comsupport.outlook-microsoft.comhelp.outlook-microsoft.comoem.outlook-microsoft.comwindws-microsoft.com
domainsapplemedia1218.comavssync3357.combbmdroid.combbmsync2727.combluesync2121.comeastmedia1221.comeastmedia3347.co.cceastmedia3347.comfacemedia.co.cckssync3343.comkssync3347.co.cckssync3347.commahee.kssync3343.co.ccmvssync8767.com

**Comment by Neo23x0** [comment]
It's a problem in  the OTX Pulse. 
https://otx.alienvault.com/pulse/576104f1d9a1b8013760a887/
I'll ask @bartblaze if he could fix it.

**Comment by bartblaze** [comment]
Entries fixed and re-added where necessary.
