### ISSUE TITLE
False positive: SMSvcHost.exe 

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [Neo23x0/signature-base#41]
20180802T15:17:40Z FELSEN LOKI: **Alert:** MODULE: ProcessScan MESSAGE: File Name IOC matched PATTERN: \\smsvchost\.exe DESC: Hexacorn Blog Entry - Homomorphic abuse http://goo.gl/1UGJVn MATCH: c:\windows\microsoft.net\framework64\v4.0.30319\smsvchost.exe

Virustotal.com: 
        Verified:       Signed
        Signing date:   09:27 22.02.2018
        Publisher:      Microsoft Corporation
        Company:        Microsoft Corporation
        Description:    SMSvcHost.exe
        Product:        Microsoft« .NET Framework
        Prod version:   4.7.3056.0
        File version:   4.7.3056.0 built by: NET472REL1
        MachineType:    32-bit
        MD5:    7EC8B56348F9298BCCA7A745C7F70E2C
        SHA1:   43DACCE26801C45666676F1AB09F53143C74D88C
        PESHA1: 545D11581566406E14165665E5A2886D9F1E1909
        PE256:  1210B3A9F034F5081BEF1F5026072B215589DB86E7B0F868B52D6F73C19ACC81
        SHA256: F677CBD94ABE25AECF08ECFBBDA063A9C032C678327A0D105CB6B3E587C44C19
        IMP:    F34D5F2D4577ED6D9CEEC516C1F5A744
        **VT detection:   0/66**
        VT link:        https://www.virustotal.com/file/f677cbd94abe25aecf08ecfbbda063a9c032c678327a0d105cb6b3e587c44c19/analysis/

**Comment by Neo23x0** [comment]
Fixed https://github.com/Neo23x0/signature-base/commit/d600b2285d9f8bf87766024d522f4e06f9d6107d
