### ISSUE TITLE
False positive: SyncAppvPublishingServer.vbs

### ISSUE THREAD

**Issue by Sir-Jective** [Neo23x0/signature-base#42]
[NOTICE]
FILE: C:\Windows\WinSxS\amd64_microsoft-windows-a..nagement-appvclient_31bf3856ad364e35_10.0.17134.1_none_b1f3037231516201\SyncAppvPublishingServer.vbs SCORE: 50 TYPE: UNKNOWN SIZE: 1720
FIRST_BYTES: 272d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d / '-------------------
MD5: 20c4fe2b130d9f0c92d7629e71afbb66
SHA1: f01de532969553083cf7906b2709940f0a41b083
SHA256: b8a5c42bf6f7a14ba73660be29f5c061d30b41c6d14e42b880a4ea522f43ce66 CREATED: Thu Apr 12 01:35:10 2018 MODIFIED: Thu Apr 12 01:35:10 2018 ACCESSED: Thu Apr 12 01:35:10 2018
REASON_1: Yara Rule MATCH: WScript_Shell_PowerShell_Combo SUBSCORE: 50
DESCRIPTION: Detects malware from Middle Eastern campaign reported by Talos REF: http://blog.talosintelligence.com/2018/02/targeted-attacks-in-middle-east.html
MATCHES: Str1: .CreateObject("WScript.Shell") Str2: powershell.exe

according to https://www.virustotal.com/de/file/b8a5c42bf6f7a14ba73660be29f5c061d30b41c6d14e42b880a4ea522f43ce66/analysis/
, this file belongs to the Microsoft Corporation software catalogue. 
But the file has been deleted, so I can't upload it.

**Comment by Neo23x0** [comment]
Fixed with https://github.com/Neo23x0/signature-base/commit/8ddab9bd5a7aee983bfd0fd9f54f44cc456b7479
