### ISSUE TITLE
undefined identifier "filename"

### ISSUE THREAD

**Issue by blacktop** [Neo23x0/signature-base#43]
A few of the yara rules fail to be compiled and throw that error:

- `yara/generic_anomalies.yar`
- `yara/general_cloaking.yar`
- `yara/thor_inverse_matches.yar`
- `yara/yara_mixed_ext_vars.yar`

This causes a segfault in go-yara with Yara version 3.7.1

**Comment by Neo23x0** [comment]
Check the README 
https://github.com/Neo23x0/signature-base#external-variables-in-yara-rules

go-yara - how do you use the rules? Just interested.

**Comment by blacktop** [comment]
😆 damn I feel dumb, thanks man! 

I am using them in this: https://github.com/malice-plugins/yara#image-tags

You do awesome work and are building some really cool things.  Keep it up man! #FOSS4LIFE

**Comment by shakidev** [comment]
> Check the README
> https://github.com/Neo23x0/signature-base#external-variables-in-yara-rules
> 
> go-yara - how do you use the rules? Just curious.

How I can start scan directory recursively without external variables?
