### ISSUE TITLE
False positives for gen_faked_versions.yar

### ISSUE THREAD

**Issue by zappeee** [Neo23x0/signature-base#5]
This rule generates a lot of false positives since it just checks if "Adobe Systems" is present.
Is it possible to add some more checks?

**Comment by Neo23x0** [comment]
It should only check for this string if the filename is "AcroRd32.exe". It shouldn't generate to many false positives.

`rule Fake_AdobeReader_EXE
    {
    meta:
        description = "Detects an fake AdobeReader executable based on filesize OR missing strings in file"
        date = "2014-09-11"
        author = "Florian Roth"
        score = 50
    strings:
        $s1 = "Adobe Systems" ascii
        $s2 = "Adobe Reader" ascii wide
    condition:
        uint16(0) == 0x5a4d and
        filename matches /AcroRd32.exe/i and
        not $s1 in (filesize-2500..filesize)
        and not $s2
}`
