### ISSUE TITLE
False Positive: In HP SureClick Files

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/signature-base#54]
[ALERT]
FILE: C:\Program Files\HP\Sure Click\4.1.0.5734\servers\firefox_.exe SCORE: 105 TYPE: EXE SIZE: 266712
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: e95e117acc1725c7e34b4ec531a640b8
SHA1: fe9bf24d823b6aa51ebe9c1b5345349bc5ab9d98
SHA256: 630e75ef3c2b2f5eea9d508e2bfa6eaa39d42e8d0b2bfa6dad5f4ca01ef61b06 CREATED: Wed Sep 26 15:03:04 2018 MODIFIED: Wed Sep 26 15:03:04 2018 ACCESSED: Tue Oct 30 08:17:17 2018
REASON_1: File Name IOC matched PATTERN: \\firefox_\.exe SUBSCORE: 45 DESC: Hexacorn Blog Entry - Homomorphic abuse http://goo.gl/1UGJVn
REASON_2: Levenshtein check - filename looks much like a well-known system file SUBSCORE: 40 ORIGINAL: firefox.exe

[ALERT]
FILE: C:\Program Files\HP\Sure Click\servers\firefox_.exe SCORE: 105 TYPE: EXE SIZE: 266712
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: e95e117acc1725c7e34b4ec531a640b8
SHA1: fe9bf24d823b6aa51ebe9c1b5345349bc5ab9d98
SHA256: 630e75ef3c2b2f5eea9d508e2bfa6eaa39d42e8d0b2bfa6dad5f4ca01ef61b06 CREATED: Wed Sep 26 15:03:04 2018 MODIFIED: Wed Sep 26 15:03:04 2018 ACCESSED: Tue Oct 30 08:17:17 2018
REASON_1: File Name IOC matched PATTERN: \\firefox_\.exe SUBSCORE: 45 DESC: Hexacorn Blog Entry - Homomorphic abuse http://goo.gl/1UGJVn
REASON_2: Levenshtein check - filename looks much like a well-known system file SUBSCORE: 40 ORIGINAL: firefox.exe

File was checked by VirusTotal, no engine could find any treat. I believe it is a false positive

**Comment by Neo23x0** [comment]
Levenshtein will still trigger - but the score will be 40 > Notice
