### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/signature-base#61]
In Spark two files will trigger some alerts:

11a1a8e958b8334207ada4f8db79a82a,C:\WINDOWS\softwaredistribution.bak\Download\2ccde37d195aba85099ad54774cf0fe2\amd64_Microsoft-Windows-Client-Features-Package~~AMD64~~10.0.17763.1\amd64_microsoft-windows-synchost_31bf3856ad364e35_10.0.17763.1_none_5a46f6fe54bbd2df\synchost.exe,90 |  
-- | --
b2716691d5f75f1f2a965923e180ce36,C:\WINDOWS\softwaredistribution.bak\Download\2ccde37d195aba85099ad54774cf0fe2\amd64_Microsoft-Windows-Client-Features-WOW64-Package~~AMD64~~10.0.17763.1\wow64_microsoft-windows-synchost_31bf3856ad364e35_10.0.17763.1_none_649ba150891c94da\synchost.exe,90

Both files were sent to lab, no malware was found. Also ok, according Virus Total scans, countercheck it by hashes. In loki, those files trigger no alert.

**Comment by Neo23x0** [comment]
Not enough info to do something with that feedback. No hash, no rule name. Closing.
