### ISSUE TITLE
get-otx-iocs.py UnicodeEncodeError

### ISSUE THREAD

**Issue by coppolak** [Neo23x0/signature-base#63]
Hello,

Whenever I run this script, I get the following error:

Traceback (most recent call last):
  File "get-otx-iocs.py", line 231, in write_iocs
    self.separator)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 10:             ordinal not in range(128)
Traceback (most recent call last):
  File "get-otx-iocs.py", line 231, in write_iocs
    self.separator)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 10:             ordinal not in range(128)

**Comment by Neo23x0** [comment]
These scripts are EOL and out of support.
