### ISSUE TITLE
Warning: USB Listener / save autorun entry

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/signature-base#64]
Spark issued the following warning:
Warning Autoruns Autoruns element located in a suspicious location
MD5:
SHA1:
SHA256:  TYPE: run_key LAUNCH_STRING: C:\Users\.......\AppData\Local\Temp\{438E237C-C9D2-4803-A1FE-EE77D929E548}\USBListener.exe -autorun IMAGE_NAME: USBListener.exe ARGUMENTS: -autorun MATCH_STRING: C:\Users\......\AppData\Local\Temp ENTRY: USBListener LOCATION: CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run IMAGE_PATH: C:\Users\.....\AppData\Local\Temp\{438E237C-C9D2-4803-A1FE-EE77D929E548}\USBListener.exe

This belongs to the legitimate program called: "Drive Security" a virus scanner implemented on an encrypted USB stick. I counterchecked the location with the manufacturer. It is a typical and save entry. May consider it for white listing. THANKS

**Comment by Neo23x0** [comment]
It's so rare, I wouldn't whitelist it. I'd recommend every user to filter that FP.
