### ISSUE TITLE
Greenbug false positive

### ISSUE THREAD

**Issue by wesinator** [Neo23x0/signature-base#68]
[29f12ccdfad0a45edff6dbbc95a82d2820b2d3d008c9661b531f452dfcc9c6a2](https://www.virustotal.com/gui/file/29f12ccdfad0a45edff6dbbc95a82d2820b2d3d008c9661b531f452dfcc9c6a2/detection)

Seems to be matching on https://github.com/Neo23x0/signature-base/blob/253371fef1bb7bd32aa52ec38bdcec674c69a47b/yara/apt_greenbug.yar#L48

**Comment by Neo23x0** [comment]
Strange, I can't make that rule hit locally on that sample

**Comment by Neo23x0** [comment]
Ah, the rule on VT is different from the one in signature-base. It was in the set `Testing`, which means that it was the unfinished rule that was left in the rule set up there. I adjusted it.
