### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by mime-frame** [Neo23x0/signature-base#7]
**apt_ham_tofu_chches.yar:Ham_backdoor**
484acf6af85a29ac52f3cf054dfde9d3
f13f5ac8b89c9ac8d02d1ef7cf9bdf0a
c2ba43865243a94d980c763f0b8c8493
1d398e4352f96ebf4e81f8e054c7f1d3
964ad15d1eb90520f8b7dc9739157629
a445263326301bf126ff4721b5644f90
1f2c388084a1bc978751d4c9465d127c
bee7b3dd24b420fac027cd72bc8d91e6

**crime_petya_ransom.yar:Petya_Ransomware**
abf64234f3462571e66527828040219b

**gen_faked_versions.yar:Fake_AdobeReader_EXE**
4f996b50c3f00e1776e1e1bae8cd1554
e53934afd93659e00305d858e89f7655
ca0c67ba7aeba6aed5ddb852e6eea811
124e70674c0cafdac4c0c8f8d95f0ba3
8a7c310e9ca50ceddcdb4f453e13036c

**gen_faked_versions.yar:Fake_FlashPlayerUpdaterService_EXE**
cc2bada495f53719836fac0999f67480
874b1d3b016bb6051eed24e6f94da18b
7eb7a3b01751889c6459c51a74cc87fa
89ecfb35517f62c3802b227f288b750e

**gen_rats_malwareconfig.yar:RAT_Sakula**
e32ad11b4d445d47fee3ff3608a16989
d8df9c697e4070b5ae4e30bf8e1c2e1b

**thor-hacktools.yar:lsadump**
fc55e571f4965b3f31822fc5f0b1b14c

**Comment by Neo23x0** [comment]
Thanks - countermeasures applied

**Comment by mime-frame** [comment]
@Neo23x0 thanks!
