### ISSUE TITLE
fp about two rules

### ISSUE THREAD

**Issue by ihacku** [Neo23x0/signature-base#75]
SPARK: Warning: MODULE: ProcessCheck MESSAGE: YARA rule match on process memory SCORE: 75 NAME: ApplicationFrameHost.exe DESC: - PID: 5180 CMD: C:\Windows\system32\ApplicationFrameHost.exe -Embedding RULE: hatman_dividers

SPARK: Warning: MODULE: ProcessCheck MESSAGE: YARA rule match on process memory SCORE: 75 NAME: WeChat.exe DESC: - PID: 2964 CMD: "D:\Program Files (x86)\Tencent\WeChat\WeChat.exe"  RULE: hatman_dividers
Download url https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

SPARK: Warning: MODULE: ProcessCheck MESSAGE: YARA rule match on process memory SCORE: 75 NAME: TencentDocs.exe DESC: - PID: 10340 CMD: "C:\Program Files (x86)\Tencent\TencentDocs\TencentDocs.exe" --minibrowsertype=browser --channel=722318 --client-id=qq --user-agent-extra=TxDocsPC/1.0.0.300 --no-sandbox /prefetch:1 --cache-path=C:\Users\xxx\AppData\Local\Tencent\TencentDocs\UserData   RULE: hatman_dividers
Download url https://qd.myapp.com/myapp/qqteam/TencentDocs/Down/TencentDocsSetup.exe

SPARK: Warning: MODULE: Filescan MESSAGE: Suspicious file found FILE: C:\Program Files (x86)\Sangfor\SSL\RemoteAppClient\SRAPSession.exe SCORE: 75 MD5: da4b4b9ada092abf082bf79562d67226 SHA1: 9ee8de0c27a1813ffccfecc79f116cdd021c4e78 SHA256: 2a44b41df86d150f92530ac485e2149574d63d8d2944e5fb5e25e9276d20d576 SIZE: 271640 TYPE: UNKNOWN FIRSTBYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ CREATED: 2017-12-01T08:29:44Z MODIFIED: 2017-12-01T08:29:44Z ACCESSED: 2019-08-24T12:24:15Z EXT: .exe REASON_1: YARA rule IronTiger_PlugX_DosEmulator / Iron Tiger Malware - PlugX DosEmulator MATCHED_1: Str1: "Fail,Error Code = %d." SUBSCORE_1: 75 REF_1: http://goo.gl/T5fSJC

SPARK: Warning: MODULE: Filescan MESSAGE: Suspicious file found FILE: C:\Program Files (x86)\Sangfor\SSL\RemoteAppClient\SfRemoteAppClient.exe SCORE: 75 MD5: 6a62b6e77720bdf907900bef48d56acb SHA1: 9193cdfa9b5c373d208a7ca1f9938f0dd5d34431 SHA256: 3e78facdbc9a07735b55d03d273b9c225aca76816431ae573da1c5fb9ee5bfc5 SIZE: 543000 TYPE: UNKNOWN FIRSTBYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ CREATED: 2017-12-01T08:24:30Z MODIFIED: 2017-12-01T08:24:30Z ACCESSED: 2019-08-24T12:24:15Z EXT: .exe REASON_1: YARA rule IronTiger_PlugX_DosEmulator / Iron Tiger Malware - PlugX DosEmulator MATCHED_1: Str1: "Fail,Error Code = %d." SUBSCORE_1: 75 REF_1: http://goo.gl/T5fSJC

SPARK: Warning: MODULE: Filescan MESSAGE: Suspicious file found FILE: C:\Program Files (x86)\Sangfor\SSL\RemoteAppClient\SfRemoteAppSession.exe SCORE: 75 MD5: 034c67c6aba4c97a605ac46f0586301b SHA1: 15455c0c64de4acb71dd79e8a122e1de4a4fd516 SHA256: 53e3ac0b78edc741f776a2738ed8bf227b51796c93139a4cd2c84db1889b8157 SIZE: 307992 TYPE: UNKNOWN FIRSTBYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ CREATED: 2017-12-01T08:25:50Z MODIFIED: 2017-12-01T08:25:50Z ACCESSED: 2019-08-24T12:24:16Z EXT: .exe REASON_1: YARA rule IronTiger_PlugX_DosEmulator / Iron Tiger Malware - PlugX DosEmulator MATCHED_1: Str1: "Fail,Error Code = %d." SUBSCORE_1: 75 REF_1: http://goo.gl/T5fSJC

**Comment by ihacku** [comment]
one more fp about rule hatman_dividers
SPARK: Warning: MODULE: ProcessCheck MESSAGE: YARA rule match on process memory SCORE: 75 NAME: lsass.exe DESC: - PID: 588 CMD: C:\Windows\system32\lsass.exe RULE: hatman_dividers REFERENCE: - TAGS:  USER: NT AUTHORITY\SYSTE
https://www.virustotal.com/gui/file/09835a43e1a17396bdc88bb38ef66ea8854913040347d9893ebf8550d0aa1452/detection

**Comment by Neo23x0** [comment]
It's kinda funny, because hatman_dividers is a private YARA rule

https://github.com/Neo23x0/signature-base/blob/c2634bfa232693ed03f189091384c50a73878d75/yara/apt_hatman.yar#L38

**Comment by wesinator** [comment]
> It's kinda funny, because hatman_dividers is a private YARA rule
> 
> https://github.com/Neo23x0/signature-base/blob/c2634bfa232693ed03f189091384c50a73878d75/yara/apt_hatman.yar#L38

@Neo23x0 so does Spark not ignore private rules ?
