### ISSUE TITLE
Some false positive in Process Check

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/signature-base#77]
First time approximately 8 processes issued a warning (all with score 75). Processes were originated from Windows, HP, beside others. All warnings were triggered by hatman_dividers. Two examples can be found below.

Warning ProcessCheck YARA rule match on process memory SCORE: 75 NAME: SearchUI.exe DESC: - PID: 12852 CMD: "C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe" -ServerName:CortanaUI.AppXa50dqqa5gqv4a428c9y1jjw7m3btvepj.mca RULE: hatman_dividers REFERENCE: - TAGS:  USER:

Warning ProcessCheck YARA rule match on process memory SCORE: 75 NAME: DPAgent.exe DESC: - PID: 14856 CMD: "c:\program files (x86)\hp\hp protecttools security manager\bin\dpagent.exe" RULE: hatman_dividers REFERENCE: - USER

**Comment by Neo23x0** [comment]
Known issue https://github.com/Neo23x0/signature-base/issues/71 and https://github.com/Neo23x0/signature-base/issues/75 - will be fixed soon.
