### ISSUE TITLE
Asking for Yara rule or whitepaper related to APT32 sample

### ISSUE THREAD

**Issue by nguyenl95** [Neo23x0/signature-base#78]
Hi, I was researching about APT32 and found your Yara rule on an interesting sample.
It saying that it's an internal research, however that was long time ago, I wonder if you could publish those Yara rule or whitepaper relate to the case.

Sample: 6b64382e0d7fe3d455c8065625d91ca3
Yara rule: APT_OceanLotus_ISSUTIL_Sep18
https://www.virustotal.com/gui/file/4e692aa0c2b858917235b4cc2befe649c1fc3df90d6c42d0f329cde57156d752/community

PS: I found this whitepaper, but it's not really related to the sample above.
https://s7d2.scene7.com/is/content/cylance/prod/cylance-web/en-us/resources/knowledge-center/resource-library/white-papers/OceanLotus-Steganography-Malware-Analysis-White-Paper.pdf

**Comment by Neo23x0** [comment]
No, sorry. "Internal Research" often means that we've got that sample from a trusted partner or digged it up with other internal rules.

**Comment by nguyenl95** [comment]
That's okay. Thanks for clarifying.
