### ISSUE TITLE
undefined identifier "PEFILE"

### ISSUE THREAD

**Issue by xl7dev** [Neo23x0/signature-base#8]
[INFO] Initializing Yara rule gen_mimikittenz.yar
Traceback (most recent call last):
  File "loki.py", line 971, in initialize_yara_rules
    'md5': dummy
SyntaxError: /Users/xxxx/tools/Loki/./signature-base/yara/gen_mimipenguin.yar(10835): undefined identifier "PEFILE"

**Comment by Neo23x0** [comment]
Fixed - thanks
