### ISSUE TITLE
False Positive: spark-core-util.exe labeled as Trojan by some AV vendors

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/signature-base#81]
A couple of days ago, first time spark-core-util.exe (SHA-256: 9B4D9812D742679F2277D00454E764C3AD2C7511FB8035CA5713F8D226A72B86) was labeld as generic Trojan (Trojan.GenericKD.32703131) by two AV engines (Bitdefender and HitmanPro) on my computer. I asked both companies to whitelist it by e-mail. From Bitdefender so far no reply. HitmanPro answered today, that they have whitelisted it for their engine. However, they told me that some more AV scanner have already labeled this file as malicious. I suggest to take steps for whitelisting. I sent a second mail today to Bitdefender. So long as the file is not whitelisted, it will be difficult to use spark-core, because it triggers the AV engines in alert.

**Comment by Neo23x0** [comment]
Obsolete
