### ISSUE TITLE
MZ uint16 scope: some rules hit off ruleset itself

### ISSUE THREAD

**Issue by wesinator** [Neo23x0/signature-base#82]
The industroyer yara ruleset submitted to VT https://www.virustotal.com/gui/search/f093e76bf030473c042aca186d8face41348aedddeb60711eaac1b01706cf4c2 matched on Industroyer_Portscan_3_Output , Industroyer_Malware_5 , even though the second rule has uint16 MZ condition

**Comment by Neo23x0** [comment]
VT issue
