### ISSUE TITLE
Certain rules that pass build-rules.py checks crash Loki

### ISSUE THREAD

**Issue by malvidin** [Neo23x0/signature-base#88]
If certain escaped characters are added to the metadata (https://github.com/VirusTotal/yara-python/issues/135), it crashes Python when yara-python tries to match. 

If a related rule was created in this repository, it passes the compilation checks, but would crash Loki or any other Python based system that uses these signatures.

Calling `compiledRules.match(data='')` a couple times in build-rules.py would ensure that rules don't get accepted that would crash Loki.  Wrapping it in a try/except doesn't help, as it crashes the interpreter.

**Comment by Neo23x0** [comment]
I review every rule and wouldn't accept rules with these values in the meta data. Thanks for the heads up.
